version: '3.8'

name: morsh_ci


x-agent-image: &Agent_Image "${DOCKER_IMG_agent:-morsh92/jenkins-agent-dind:alpine}" 
x-agent-user: &Agent_User "${DOCKER_USER_agent:-root}"
x-agent-1-cpu: &Agent_1_CPU "${DOCKER_agent_1_CPUS:-1}"
x-agent-1-mem: &Agent_1_MEM "${DOCKER_agent_1_MEMORY:-512MB}"
x-agent-2-cpu: &Agent_2_CPU "${DOCKER_agent_2_CPUS:-1}"
x-agent-2-mem: &Agent_2_MEM "${DOCKER_agent_2_MEMORY:-512MB}"
x-agent-1-env: &Agent_1_ENV
  - JENKINS_SECRET=863a125ab2372dd6cdc00736925d254873cd986a0282422344e23d9de26756b0
  - JENKINS_URL=http://master:8080
  - JENKINS_AGENT_NAME=agent-1
  - JENKINS_AGENT_WORKDIR=/home/jenkins
x-agent-2-env: &Agent_2_ENV
  - JENKINS_SECRET=aacde6525e87b530d3616be758cc7df4c46b3b53ee76c7b8e663ebe9db1ab8ba
  - JENKINS_URL=http://master:8080
  - JENKINS_AGENT_NAME=agent-2
  - JENKINS_AGENT_WORKDIR=/home/jenkins


x-logging: &logging
 driver: "json-file"
 options:
   max-size: "100m"
   max-file: "1"


services:
 jenkins-main:
  image: "${DOCKER_IMG_main:-jenkins/jenkins:lts}"
  privileged: true
  user: "${DOCKER_USER_main:-root}"
  deploy:
    resources:
      limits:
        cpus: "${DOCKER_main_CPUS:-2}"
        memory: "${DOCKER_main_MEMORY:-2GB}"
  restart: unless-stopped
  healthcheck:
    test: curl -I http://master:8080/login --max-time 5 | grep 200
    interval: 5s
    timeout: 10s
    start_period: 180s
    retries: 10
  sysctls:
   - net.ipv4.ip_local_port_range=1024 65000
   - net.ipv4.conf.all.accept_redirects=0
   - net.ipv4.conf.all.secure_redirects=0
   - net.ipv4.conf.all.send_redirects=0
  networks:
   backend:
     aliases:
        - master
   frontend:
  ports:
   - "8080:8080"
   - "50000:50000"
  volumes:   
   - ./home:/var/jenkins_home:rw
   - /var/run/docker.sock:/var/run/docker.sock
  logging: *logging

 
 jenkins-agent-1: 
   image: *Agent_Image
   user: *Agent_User
   privileged: true
   deploy: 
    resources:
      limits:
        cpus: *Agent_1_CPU
        memory: *Agent_1_MEM
   restart:  unless-stopped
   depends_on:
    jenkins-main:
     condition: service_healthy
   sysctls: 
    - net.ipv4.ip_local_port_range=1024 65000
    - net.ipv4.conf.all.accept_redirects=0
    - net.ipv4.conf.all.secure_redirects=0
    - net.ipv4.conf.all.send_redirects=0
   environment: *Agent_1_ENV
   networks: 
    frontend:
    backend:
      aliases:
         - slave-1
   logging: *logging

 jenkins-agent-2:
  image: *Agent_Image
  user: *Agent_User 
  privileged: true
  deploy: 
    resources:
      limits:
        cpus:  *Agent_2_CPU
        memory: *Agent_2_MEM
  restart:  unless-stopped
  depends_on:
    jenkins-main:
     condition: service_healthy
  sysctls:
    - net.ipv4.ip_local_port_range=1024 65000
    - net.ipv4.conf.all.accept_redirects=0
    - net.ipv4.conf.all.secure_redirects=0
    - net.ipv4.conf.all.send_redirects=0 
  environment: *Agent_2_ENV
  networks:
    frontend:
    backend:
      aliases:
         - slave-2
  logging: *logging
  


networks:
 frontend:
   driver: bridge
   driver_opts:
      com.docker.network.enable_ipv6: "false"
   ipam:
     driver: default
     config:
      - subnet: 10.212.21.0/28
 backend:
   internal: true
   driver: bridge
   driver_opts:
     com.docker.network.enable_ipv6: "false"
   ipam:
     driver: default
     config:
      - subnet: 10.111.111.0/28       
  
  
  